version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-s3
    restart: unless-stopped
    ports:
      - "9300:9000"      # MinIO API端口
      - "9301:9001"      # MinIO控制台端口
    environment:
      # MinIO访问凭证
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
      # MinIO区域设置
      MINIO_REGION: us-east-1
      # 控制台地址
      MINIO_BROWSER_REDIRECT_URL: http://localhost:9001
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 20s
    networks:
      - app-network

  # 可选：创建默认存储桶的初始化容器
  minio-init:
    image: minio/mc:latest
    container_name: minio-init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin123;
      /usr/bin/mc mb myminio/default-bucket --ignore-existing;
      /usr/bin/mc anonymous set download myminio/default-bucket;
      echo 'MinIO初始化完成';
      "
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6979:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-network

  postgresql:
    image: postgres:15-alpine
    container_name: postgresql-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      # PostgreSQL数据库配置
      POSTGRES_DB: qc_admin
      POSTGRES_USER: qc_admin
      POSTGRES_PASSWORD: qc_admin123
      # 可选：设置时区
      TZ: Asia/Shanghai
      # 关键：禁用DNS反向查询以提高连接速度
      POSTGRES_HOST_AUTH_METHOD: md5
    command: >
      postgres
      -c log_hostname=off
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c maintenance_work_mem=64MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c default_statistics_target=100
      -c random_page_cost=1.1
      -c effective_io_concurrency=200
      -c work_mem=4MB
      -c min_wal_size=1GB
      -c max_wal_size=4GB
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qc_admin -d qc_admin"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app-network

volumes:
  minio_data:
    driver: local
  minio_config:
    driver: local
  redis_data:
    driver: local
  postgresql_data:
    driver: local

networks:
  app-network:
    driver: bridge
