// Code generated by ent, DO NOT EDIT.

package intercept

import (
	"context"
	"fmt"

	"go-backend/database/ent"
	"go-backend/database/ent/address"
	"go-backend/database/ent/apiauth"
	"go-backend/database/ent/area"
	"go-backend/database/ent/attachment"
	"go-backend/database/ent/clientdevice"
	"go-backend/database/ent/credential"
	"go-backend/database/ent/logging"
	"go-backend/database/ent/loginrecord"
	"go-backend/database/ent/oauthapplication"
	"go-backend/database/ent/oauthauthorizationcode"
	"go-backend/database/ent/oauthprovider"
	"go-backend/database/ent/oauthstate"
	"go-backend/database/ent/oauthtoken"
	"go-backend/database/ent/oauthuser"
	"go-backend/database/ent/oauthuserauthorization"
	"go-backend/database/ent/permission"
	"go-backend/database/ent/predicate"
	"go-backend/database/ent/role"
	"go-backend/database/ent/rolepermission"
	"go-backend/database/ent/scan"
	"go-backend/database/ent/scope"
	"go-backend/database/ent/station"
	"go-backend/database/ent/subway"
	"go-backend/database/ent/subwaystation"
	"go-backend/database/ent/systemmonitor"
	"go-backend/database/ent/user"
	"go-backend/database/ent/userrole"
	"go-backend/database/ent/verifycode"
	"go-backend/database/ent/workflowapplication"
	"go-backend/database/ent/workflowedge"
	"go-backend/database/ent/workflowexecution"
	"go-backend/database/ent/workflowexecutionlog"
	"go-backend/database/ent/workflownode"
	"go-backend/database/ent/workflownodeexecution"
	"go-backend/database/ent/workflowversion"

	"entgo.io/ent/dialect/sql"
)

// The Query interface represents an operation that queries a graph.
// By using this interface, users can write generic code that manipulates
// query builders of different types.
type Query interface {
	// Type returns the string representation of the query type.
	Type() string
	// Limit the number of records to be returned by this query.
	Limit(int)
	// Offset to start from.
	Offset(int)
	// Unique configures the query builder to filter duplicate records.
	Unique(bool)
	// Order specifies how the records should be ordered.
	Order(...func(*sql.Selector))
	// WhereP appends storage-level predicates to the query builder. Using this method, users
	// can use type-assertion to append predicates that do not depend on any generated package.
	WhereP(...func(*sql.Selector))
}

// The Func type is an adapter that allows ordinary functions to be used as interceptors.
// Unlike traversal functions, interceptors are skipped during graph traversals. Note that the
// implementation of Func is different from the one defined in entgo.io/ent.InterceptFunc.
type Func func(context.Context, Query) error

// Intercept calls f(ctx, q) and then applied the next Querier.
func (f Func) Intercept(next ent.Querier) ent.Querier {
	return ent.QuerierFunc(func(ctx context.Context, q ent.Query) (ent.Value, error) {
		query, err := NewQuery(q)
		if err != nil {
			return nil, err
		}
		if err := f(ctx, query); err != nil {
			return nil, err
		}
		return next.Query(ctx, q)
	})
}

// The TraverseFunc type is an adapter to allow the use of ordinary function as Traverser.
// If f is a function with the appropriate signature, TraverseFunc(f) is a Traverser that calls f.
type TraverseFunc func(context.Context, Query) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseFunc) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseFunc) Traverse(ctx context.Context, q ent.Query) error {
	query, err := NewQuery(q)
	if err != nil {
		return err
	}
	return f(ctx, query)
}

// The APIAuthFunc type is an adapter to allow the use of ordinary function as a Querier.
type APIAuthFunc func(context.Context, *ent.APIAuthQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f APIAuthFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.APIAuthQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.APIAuthQuery", q)
}

// The TraverseAPIAuth type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAPIAuth func(context.Context, *ent.APIAuthQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAPIAuth) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAPIAuth) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.APIAuthQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.APIAuthQuery", q)
}

// The AddressFunc type is an adapter to allow the use of ordinary function as a Querier.
type AddressFunc func(context.Context, *ent.AddressQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AddressFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AddressQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AddressQuery", q)
}

// The TraverseAddress type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAddress func(context.Context, *ent.AddressQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAddress) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAddress) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AddressQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AddressQuery", q)
}

// The AreaFunc type is an adapter to allow the use of ordinary function as a Querier.
type AreaFunc func(context.Context, *ent.AreaQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AreaFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AreaQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AreaQuery", q)
}

// The TraverseArea type is an adapter to allow the use of ordinary function as Traverser.
type TraverseArea func(context.Context, *ent.AreaQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseArea) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseArea) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AreaQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AreaQuery", q)
}

// The AttachmentFunc type is an adapter to allow the use of ordinary function as a Querier.
type AttachmentFunc func(context.Context, *ent.AttachmentQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f AttachmentFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.AttachmentQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.AttachmentQuery", q)
}

// The TraverseAttachment type is an adapter to allow the use of ordinary function as Traverser.
type TraverseAttachment func(context.Context, *ent.AttachmentQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseAttachment) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseAttachment) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.AttachmentQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.AttachmentQuery", q)
}

// The ClientDeviceFunc type is an adapter to allow the use of ordinary function as a Querier.
type ClientDeviceFunc func(context.Context, *ent.ClientDeviceQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ClientDeviceFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ClientDeviceQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ClientDeviceQuery", q)
}

// The TraverseClientDevice type is an adapter to allow the use of ordinary function as Traverser.
type TraverseClientDevice func(context.Context, *ent.ClientDeviceQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseClientDevice) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseClientDevice) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ClientDeviceQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ClientDeviceQuery", q)
}

// The CredentialFunc type is an adapter to allow the use of ordinary function as a Querier.
type CredentialFunc func(context.Context, *ent.CredentialQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f CredentialFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.CredentialQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.CredentialQuery", q)
}

// The TraverseCredential type is an adapter to allow the use of ordinary function as Traverser.
type TraverseCredential func(context.Context, *ent.CredentialQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseCredential) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseCredential) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.CredentialQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.CredentialQuery", q)
}

// The LoggingFunc type is an adapter to allow the use of ordinary function as a Querier.
type LoggingFunc func(context.Context, *ent.LoggingQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f LoggingFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.LoggingQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.LoggingQuery", q)
}

// The TraverseLogging type is an adapter to allow the use of ordinary function as Traverser.
type TraverseLogging func(context.Context, *ent.LoggingQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseLogging) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseLogging) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.LoggingQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.LoggingQuery", q)
}

// The LoginRecordFunc type is an adapter to allow the use of ordinary function as a Querier.
type LoginRecordFunc func(context.Context, *ent.LoginRecordQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f LoginRecordFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.LoginRecordQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.LoginRecordQuery", q)
}

// The TraverseLoginRecord type is an adapter to allow the use of ordinary function as Traverser.
type TraverseLoginRecord func(context.Context, *ent.LoginRecordQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseLoginRecord) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseLoginRecord) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.LoginRecordQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.LoginRecordQuery", q)
}

// The OauthApplicationFunc type is an adapter to allow the use of ordinary function as a Querier.
type OauthApplicationFunc func(context.Context, *ent.OauthApplicationQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OauthApplicationFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OauthApplicationQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OauthApplicationQuery", q)
}

// The TraverseOauthApplication type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOauthApplication func(context.Context, *ent.OauthApplicationQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOauthApplication) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOauthApplication) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OauthApplicationQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OauthApplicationQuery", q)
}

// The OauthAuthorizationCodeFunc type is an adapter to allow the use of ordinary function as a Querier.
type OauthAuthorizationCodeFunc func(context.Context, *ent.OauthAuthorizationCodeQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OauthAuthorizationCodeFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OauthAuthorizationCodeQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OauthAuthorizationCodeQuery", q)
}

// The TraverseOauthAuthorizationCode type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOauthAuthorizationCode func(context.Context, *ent.OauthAuthorizationCodeQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOauthAuthorizationCode) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOauthAuthorizationCode) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OauthAuthorizationCodeQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OauthAuthorizationCodeQuery", q)
}

// The OauthProviderFunc type is an adapter to allow the use of ordinary function as a Querier.
type OauthProviderFunc func(context.Context, *ent.OauthProviderQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OauthProviderFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OauthProviderQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OauthProviderQuery", q)
}

// The TraverseOauthProvider type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOauthProvider func(context.Context, *ent.OauthProviderQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOauthProvider) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOauthProvider) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OauthProviderQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OauthProviderQuery", q)
}

// The OauthStateFunc type is an adapter to allow the use of ordinary function as a Querier.
type OauthStateFunc func(context.Context, *ent.OauthStateQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OauthStateFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OauthStateQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OauthStateQuery", q)
}

// The TraverseOauthState type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOauthState func(context.Context, *ent.OauthStateQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOauthState) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOauthState) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OauthStateQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OauthStateQuery", q)
}

// The OauthTokenFunc type is an adapter to allow the use of ordinary function as a Querier.
type OauthTokenFunc func(context.Context, *ent.OauthTokenQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OauthTokenFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OauthTokenQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OauthTokenQuery", q)
}

// The TraverseOauthToken type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOauthToken func(context.Context, *ent.OauthTokenQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOauthToken) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOauthToken) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OauthTokenQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OauthTokenQuery", q)
}

// The OauthUserFunc type is an adapter to allow the use of ordinary function as a Querier.
type OauthUserFunc func(context.Context, *ent.OauthUserQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OauthUserFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OauthUserQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OauthUserQuery", q)
}

// The TraverseOauthUser type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOauthUser func(context.Context, *ent.OauthUserQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOauthUser) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOauthUser) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OauthUserQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OauthUserQuery", q)
}

// The OauthUserAuthorizationFunc type is an adapter to allow the use of ordinary function as a Querier.
type OauthUserAuthorizationFunc func(context.Context, *ent.OauthUserAuthorizationQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f OauthUserAuthorizationFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.OauthUserAuthorizationQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.OauthUserAuthorizationQuery", q)
}

// The TraverseOauthUserAuthorization type is an adapter to allow the use of ordinary function as Traverser.
type TraverseOauthUserAuthorization func(context.Context, *ent.OauthUserAuthorizationQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseOauthUserAuthorization) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseOauthUserAuthorization) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.OauthUserAuthorizationQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.OauthUserAuthorizationQuery", q)
}

// The PermissionFunc type is an adapter to allow the use of ordinary function as a Querier.
type PermissionFunc func(context.Context, *ent.PermissionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f PermissionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.PermissionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.PermissionQuery", q)
}

// The TraversePermission type is an adapter to allow the use of ordinary function as Traverser.
type TraversePermission func(context.Context, *ent.PermissionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraversePermission) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraversePermission) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.PermissionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.PermissionQuery", q)
}

// The RoleFunc type is an adapter to allow the use of ordinary function as a Querier.
type RoleFunc func(context.Context, *ent.RoleQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RoleFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RoleQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RoleQuery", q)
}

// The TraverseRole type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRole func(context.Context, *ent.RoleQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRole) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRole) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RoleQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RoleQuery", q)
}

// The RolePermissionFunc type is an adapter to allow the use of ordinary function as a Querier.
type RolePermissionFunc func(context.Context, *ent.RolePermissionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f RolePermissionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.RolePermissionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.RolePermissionQuery", q)
}

// The TraverseRolePermission type is an adapter to allow the use of ordinary function as Traverser.
type TraverseRolePermission func(context.Context, *ent.RolePermissionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseRolePermission) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseRolePermission) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.RolePermissionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.RolePermissionQuery", q)
}

// The ScanFunc type is an adapter to allow the use of ordinary function as a Querier.
type ScanFunc func(context.Context, *ent.ScanQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ScanFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ScanQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ScanQuery", q)
}

// The TraverseScan type is an adapter to allow the use of ordinary function as Traverser.
type TraverseScan func(context.Context, *ent.ScanQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseScan) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseScan) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ScanQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ScanQuery", q)
}

// The ScopeFunc type is an adapter to allow the use of ordinary function as a Querier.
type ScopeFunc func(context.Context, *ent.ScopeQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f ScopeFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.ScopeQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.ScopeQuery", q)
}

// The TraverseScope type is an adapter to allow the use of ordinary function as Traverser.
type TraverseScope func(context.Context, *ent.ScopeQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseScope) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseScope) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.ScopeQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.ScopeQuery", q)
}

// The StationFunc type is an adapter to allow the use of ordinary function as a Querier.
type StationFunc func(context.Context, *ent.StationQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f StationFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.StationQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.StationQuery", q)
}

// The TraverseStation type is an adapter to allow the use of ordinary function as Traverser.
type TraverseStation func(context.Context, *ent.StationQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseStation) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseStation) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.StationQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.StationQuery", q)
}

// The SubwayFunc type is an adapter to allow the use of ordinary function as a Querier.
type SubwayFunc func(context.Context, *ent.SubwayQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SubwayFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SubwayQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SubwayQuery", q)
}

// The TraverseSubway type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSubway func(context.Context, *ent.SubwayQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSubway) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSubway) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SubwayQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SubwayQuery", q)
}

// The SubwayStationFunc type is an adapter to allow the use of ordinary function as a Querier.
type SubwayStationFunc func(context.Context, *ent.SubwayStationQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SubwayStationFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SubwayStationQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SubwayStationQuery", q)
}

// The TraverseSubwayStation type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSubwayStation func(context.Context, *ent.SubwayStationQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSubwayStation) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSubwayStation) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SubwayStationQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SubwayStationQuery", q)
}

// The SystemMonitorFunc type is an adapter to allow the use of ordinary function as a Querier.
type SystemMonitorFunc func(context.Context, *ent.SystemMonitorQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f SystemMonitorFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.SystemMonitorQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.SystemMonitorQuery", q)
}

// The TraverseSystemMonitor type is an adapter to allow the use of ordinary function as Traverser.
type TraverseSystemMonitor func(context.Context, *ent.SystemMonitorQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseSystemMonitor) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseSystemMonitor) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.SystemMonitorQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.SystemMonitorQuery", q)
}

// The UserFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserFunc func(context.Context, *ent.UserQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// The TraverseUser type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUser func(context.Context, *ent.UserQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUser) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUser) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserQuery", q)
}

// The UserRoleFunc type is an adapter to allow the use of ordinary function as a Querier.
type UserRoleFunc func(context.Context, *ent.UserRoleQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f UserRoleFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.UserRoleQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.UserRoleQuery", q)
}

// The TraverseUserRole type is an adapter to allow the use of ordinary function as Traverser.
type TraverseUserRole func(context.Context, *ent.UserRoleQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseUserRole) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseUserRole) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.UserRoleQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.UserRoleQuery", q)
}

// The VerifyCodeFunc type is an adapter to allow the use of ordinary function as a Querier.
type VerifyCodeFunc func(context.Context, *ent.VerifyCodeQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f VerifyCodeFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.VerifyCodeQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.VerifyCodeQuery", q)
}

// The TraverseVerifyCode type is an adapter to allow the use of ordinary function as Traverser.
type TraverseVerifyCode func(context.Context, *ent.VerifyCodeQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseVerifyCode) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseVerifyCode) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.VerifyCodeQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.VerifyCodeQuery", q)
}

// The WorkflowApplicationFunc type is an adapter to allow the use of ordinary function as a Querier.
type WorkflowApplicationFunc func(context.Context, *ent.WorkflowApplicationQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f WorkflowApplicationFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.WorkflowApplicationQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.WorkflowApplicationQuery", q)
}

// The TraverseWorkflowApplication type is an adapter to allow the use of ordinary function as Traverser.
type TraverseWorkflowApplication func(context.Context, *ent.WorkflowApplicationQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseWorkflowApplication) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseWorkflowApplication) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.WorkflowApplicationQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.WorkflowApplicationQuery", q)
}

// The WorkflowEdgeFunc type is an adapter to allow the use of ordinary function as a Querier.
type WorkflowEdgeFunc func(context.Context, *ent.WorkflowEdgeQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f WorkflowEdgeFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.WorkflowEdgeQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.WorkflowEdgeQuery", q)
}

// The TraverseWorkflowEdge type is an adapter to allow the use of ordinary function as Traverser.
type TraverseWorkflowEdge func(context.Context, *ent.WorkflowEdgeQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseWorkflowEdge) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseWorkflowEdge) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.WorkflowEdgeQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.WorkflowEdgeQuery", q)
}

// The WorkflowExecutionFunc type is an adapter to allow the use of ordinary function as a Querier.
type WorkflowExecutionFunc func(context.Context, *ent.WorkflowExecutionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f WorkflowExecutionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.WorkflowExecutionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.WorkflowExecutionQuery", q)
}

// The TraverseWorkflowExecution type is an adapter to allow the use of ordinary function as Traverser.
type TraverseWorkflowExecution func(context.Context, *ent.WorkflowExecutionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseWorkflowExecution) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseWorkflowExecution) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.WorkflowExecutionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.WorkflowExecutionQuery", q)
}

// The WorkflowExecutionLogFunc type is an adapter to allow the use of ordinary function as a Querier.
type WorkflowExecutionLogFunc func(context.Context, *ent.WorkflowExecutionLogQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f WorkflowExecutionLogFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.WorkflowExecutionLogQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.WorkflowExecutionLogQuery", q)
}

// The TraverseWorkflowExecutionLog type is an adapter to allow the use of ordinary function as Traverser.
type TraverseWorkflowExecutionLog func(context.Context, *ent.WorkflowExecutionLogQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseWorkflowExecutionLog) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseWorkflowExecutionLog) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.WorkflowExecutionLogQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.WorkflowExecutionLogQuery", q)
}

// The WorkflowNodeFunc type is an adapter to allow the use of ordinary function as a Querier.
type WorkflowNodeFunc func(context.Context, *ent.WorkflowNodeQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f WorkflowNodeFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.WorkflowNodeQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.WorkflowNodeQuery", q)
}

// The TraverseWorkflowNode type is an adapter to allow the use of ordinary function as Traverser.
type TraverseWorkflowNode func(context.Context, *ent.WorkflowNodeQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseWorkflowNode) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseWorkflowNode) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.WorkflowNodeQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.WorkflowNodeQuery", q)
}

// The WorkflowNodeExecutionFunc type is an adapter to allow the use of ordinary function as a Querier.
type WorkflowNodeExecutionFunc func(context.Context, *ent.WorkflowNodeExecutionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f WorkflowNodeExecutionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.WorkflowNodeExecutionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.WorkflowNodeExecutionQuery", q)
}

// The TraverseWorkflowNodeExecution type is an adapter to allow the use of ordinary function as Traverser.
type TraverseWorkflowNodeExecution func(context.Context, *ent.WorkflowNodeExecutionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseWorkflowNodeExecution) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseWorkflowNodeExecution) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.WorkflowNodeExecutionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.WorkflowNodeExecutionQuery", q)
}

// The WorkflowVersionFunc type is an adapter to allow the use of ordinary function as a Querier.
type WorkflowVersionFunc func(context.Context, *ent.WorkflowVersionQuery) (ent.Value, error)

// Query calls f(ctx, q).
func (f WorkflowVersionFunc) Query(ctx context.Context, q ent.Query) (ent.Value, error) {
	if q, ok := q.(*ent.WorkflowVersionQuery); ok {
		return f(ctx, q)
	}
	return nil, fmt.Errorf("unexpected query type %T. expect *ent.WorkflowVersionQuery", q)
}

// The TraverseWorkflowVersion type is an adapter to allow the use of ordinary function as Traverser.
type TraverseWorkflowVersion func(context.Context, *ent.WorkflowVersionQuery) error

// Intercept is a dummy implementation of Intercept that returns the next Querier in the pipeline.
func (f TraverseWorkflowVersion) Intercept(next ent.Querier) ent.Querier {
	return next
}

// Traverse calls f(ctx, q).
func (f TraverseWorkflowVersion) Traverse(ctx context.Context, q ent.Query) error {
	if q, ok := q.(*ent.WorkflowVersionQuery); ok {
		return f(ctx, q)
	}
	return fmt.Errorf("unexpected query type %T. expect *ent.WorkflowVersionQuery", q)
}

// NewQuery returns the generic Query interface for the given typed query.
func NewQuery(q ent.Query) (Query, error) {
	switch q := q.(type) {
	case *ent.APIAuthQuery:
		return &query[*ent.APIAuthQuery, predicate.APIAuth, apiauth.OrderOption]{typ: ent.TypeAPIAuth, tq: q}, nil
	case *ent.AddressQuery:
		return &query[*ent.AddressQuery, predicate.Address, address.OrderOption]{typ: ent.TypeAddress, tq: q}, nil
	case *ent.AreaQuery:
		return &query[*ent.AreaQuery, predicate.Area, area.OrderOption]{typ: ent.TypeArea, tq: q}, nil
	case *ent.AttachmentQuery:
		return &query[*ent.AttachmentQuery, predicate.Attachment, attachment.OrderOption]{typ: ent.TypeAttachment, tq: q}, nil
	case *ent.ClientDeviceQuery:
		return &query[*ent.ClientDeviceQuery, predicate.ClientDevice, clientdevice.OrderOption]{typ: ent.TypeClientDevice, tq: q}, nil
	case *ent.CredentialQuery:
		return &query[*ent.CredentialQuery, predicate.Credential, credential.OrderOption]{typ: ent.TypeCredential, tq: q}, nil
	case *ent.LoggingQuery:
		return &query[*ent.LoggingQuery, predicate.Logging, logging.OrderOption]{typ: ent.TypeLogging, tq: q}, nil
	case *ent.LoginRecordQuery:
		return &query[*ent.LoginRecordQuery, predicate.LoginRecord, loginrecord.OrderOption]{typ: ent.TypeLoginRecord, tq: q}, nil
	case *ent.OauthApplicationQuery:
		return &query[*ent.OauthApplicationQuery, predicate.OauthApplication, oauthapplication.OrderOption]{typ: ent.TypeOauthApplication, tq: q}, nil
	case *ent.OauthAuthorizationCodeQuery:
		return &query[*ent.OauthAuthorizationCodeQuery, predicate.OauthAuthorizationCode, oauthauthorizationcode.OrderOption]{typ: ent.TypeOauthAuthorizationCode, tq: q}, nil
	case *ent.OauthProviderQuery:
		return &query[*ent.OauthProviderQuery, predicate.OauthProvider, oauthprovider.OrderOption]{typ: ent.TypeOauthProvider, tq: q}, nil
	case *ent.OauthStateQuery:
		return &query[*ent.OauthStateQuery, predicate.OauthState, oauthstate.OrderOption]{typ: ent.TypeOauthState, tq: q}, nil
	case *ent.OauthTokenQuery:
		return &query[*ent.OauthTokenQuery, predicate.OauthToken, oauthtoken.OrderOption]{typ: ent.TypeOauthToken, tq: q}, nil
	case *ent.OauthUserQuery:
		return &query[*ent.OauthUserQuery, predicate.OauthUser, oauthuser.OrderOption]{typ: ent.TypeOauthUser, tq: q}, nil
	case *ent.OauthUserAuthorizationQuery:
		return &query[*ent.OauthUserAuthorizationQuery, predicate.OauthUserAuthorization, oauthuserauthorization.OrderOption]{typ: ent.TypeOauthUserAuthorization, tq: q}, nil
	case *ent.PermissionQuery:
		return &query[*ent.PermissionQuery, predicate.Permission, permission.OrderOption]{typ: ent.TypePermission, tq: q}, nil
	case *ent.RoleQuery:
		return &query[*ent.RoleQuery, predicate.Role, role.OrderOption]{typ: ent.TypeRole, tq: q}, nil
	case *ent.RolePermissionQuery:
		return &query[*ent.RolePermissionQuery, predicate.RolePermission, rolepermission.OrderOption]{typ: ent.TypeRolePermission, tq: q}, nil
	case *ent.ScanQuery:
		return &query[*ent.ScanQuery, predicate.Scan, scan.OrderOption]{typ: ent.TypeScan, tq: q}, nil
	case *ent.ScopeQuery:
		return &query[*ent.ScopeQuery, predicate.Scope, scope.OrderOption]{typ: ent.TypeScope, tq: q}, nil
	case *ent.StationQuery:
		return &query[*ent.StationQuery, predicate.Station, station.OrderOption]{typ: ent.TypeStation, tq: q}, nil
	case *ent.SubwayQuery:
		return &query[*ent.SubwayQuery, predicate.Subway, subway.OrderOption]{typ: ent.TypeSubway, tq: q}, nil
	case *ent.SubwayStationQuery:
		return &query[*ent.SubwayStationQuery, predicate.SubwayStation, subwaystation.OrderOption]{typ: ent.TypeSubwayStation, tq: q}, nil
	case *ent.SystemMonitorQuery:
		return &query[*ent.SystemMonitorQuery, predicate.SystemMonitor, systemmonitor.OrderOption]{typ: ent.TypeSystemMonitor, tq: q}, nil
	case *ent.UserQuery:
		return &query[*ent.UserQuery, predicate.User, user.OrderOption]{typ: ent.TypeUser, tq: q}, nil
	case *ent.UserRoleQuery:
		return &query[*ent.UserRoleQuery, predicate.UserRole, userrole.OrderOption]{typ: ent.TypeUserRole, tq: q}, nil
	case *ent.VerifyCodeQuery:
		return &query[*ent.VerifyCodeQuery, predicate.VerifyCode, verifycode.OrderOption]{typ: ent.TypeVerifyCode, tq: q}, nil
	case *ent.WorkflowApplicationQuery:
		return &query[*ent.WorkflowApplicationQuery, predicate.WorkflowApplication, workflowapplication.OrderOption]{typ: ent.TypeWorkflowApplication, tq: q}, nil
	case *ent.WorkflowEdgeQuery:
		return &query[*ent.WorkflowEdgeQuery, predicate.WorkflowEdge, workflowedge.OrderOption]{typ: ent.TypeWorkflowEdge, tq: q}, nil
	case *ent.WorkflowExecutionQuery:
		return &query[*ent.WorkflowExecutionQuery, predicate.WorkflowExecution, workflowexecution.OrderOption]{typ: ent.TypeWorkflowExecution, tq: q}, nil
	case *ent.WorkflowExecutionLogQuery:
		return &query[*ent.WorkflowExecutionLogQuery, predicate.WorkflowExecutionLog, workflowexecutionlog.OrderOption]{typ: ent.TypeWorkflowExecutionLog, tq: q}, nil
	case *ent.WorkflowNodeQuery:
		return &query[*ent.WorkflowNodeQuery, predicate.WorkflowNode, workflownode.OrderOption]{typ: ent.TypeWorkflowNode, tq: q}, nil
	case *ent.WorkflowNodeExecutionQuery:
		return &query[*ent.WorkflowNodeExecutionQuery, predicate.WorkflowNodeExecution, workflownodeexecution.OrderOption]{typ: ent.TypeWorkflowNodeExecution, tq: q}, nil
	case *ent.WorkflowVersionQuery:
		return &query[*ent.WorkflowVersionQuery, predicate.WorkflowVersion, workflowversion.OrderOption]{typ: ent.TypeWorkflowVersion, tq: q}, nil
	default:
		return nil, fmt.Errorf("unknown query type %T", q)
	}
}

type query[T any, P ~func(*sql.Selector), R ~func(*sql.Selector)] struct {
	typ string
	tq  interface {
		Limit(int) T
		Offset(int) T
		Unique(bool) T
		Order(...R) T
		Where(...P) T
	}
}

func (q query[T, P, R]) Type() string {
	return q.typ
}

func (q query[T, P, R]) Limit(limit int) {
	q.tq.Limit(limit)
}

func (q query[T, P, R]) Offset(offset int) {
	q.tq.Offset(offset)
}

func (q query[T, P, R]) Unique(unique bool) {
	q.tq.Unique(unique)
}

func (q query[T, P, R]) Order(orders ...func(*sql.Selector)) {
	rs := make([]R, len(orders))
	for i := range orders {
		rs[i] = orders[i]
	}
	q.tq.Order(rs...)
}

func (q query[T, P, R]) WhereP(ps ...func(*sql.Selector)) {
	p := make([]P, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	q.tq.Where(p...)
}
