redis:
  addr: "localhost:6379"        # Redis服务器地址
  password: ""                  # Redis密码（如果有的话）
  db: 0                        # Redis数据库索引
  pool_size: 10                # 连接池大小
  min_idle_conns: 5            # 最小空闲连接数
  read_timeout: 3              # 读超时（秒）
  write_timeout: 3             # 写超时（秒）
  idle_timeout: 300            # 空闲超时（秒）