// Code generated by ent, DO NOT EDIT.

package oauthuserauthorization

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the oauthuserauthorization type in the database.
	Label = "oauth_user_authorization"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// FieldCreateBy holds the string denoting the create_by field in the database.
	FieldCreateBy = "create_by"
	// FieldUpdateTime holds the string denoting the update_time field in the database.
	FieldUpdateTime = "update_time"
	// FieldUpdateBy holds the string denoting the update_by field in the database.
	FieldUpdateBy = "update_by"
	// FieldDeleteTime holds the string denoting the delete_time field in the database.
	FieldDeleteTime = "delete_time"
	// FieldDeleteBy holds the string denoting the delete_by field in the database.
	FieldDeleteBy = "delete_by"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldApplicationID holds the string denoting the application_id field in the database.
	FieldApplicationID = "application_id"
	// FieldAuthorizedAt holds the string denoting the authorized_at field in the database.
	FieldAuthorizedAt = "authorized_at"
	// FieldUsageState holds the string denoting the usage_state field in the database.
	FieldUsageState = "usage_state"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeApplication holds the string denoting the application edge name in mutations.
	EdgeApplication = "application"
	// EdgeCode holds the string denoting the code edge name in mutations.
	EdgeCode = "code"
	// EdgeToken holds the string denoting the token edge name in mutations.
	EdgeToken = "token"
	// Table holds the table name of the oauthuserauthorization in the database.
	Table = "oauth_user_authorizations"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "oauth_user_authorizations"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "sys_users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// ApplicationTable is the table that holds the application relation/edge.
	ApplicationTable = "oauth_user_authorizations"
	// ApplicationInverseTable is the table name for the OauthApplication entity.
	// It exists in this package in order to avoid circular dependency with the "oauthapplication" package.
	ApplicationInverseTable = "oauth_applications"
	// ApplicationColumn is the table column denoting the application relation/edge.
	ApplicationColumn = "application_id"
	// CodeTable is the table that holds the code relation/edge.
	CodeTable = "oauth_authorization_codes"
	// CodeInverseTable is the table name for the OauthAuthorizationCode entity.
	// It exists in this package in order to avoid circular dependency with the "oauthauthorizationcode" package.
	CodeInverseTable = "oauth_authorization_codes"
	// CodeColumn is the table column denoting the code relation/edge.
	CodeColumn = "oauth_user_authorization_code"
	// TokenTable is the table that holds the token relation/edge.
	TokenTable = "oauth_tokens"
	// TokenInverseTable is the table name for the OauthToken entity.
	// It exists in this package in order to avoid circular dependency with the "oauthtoken" package.
	TokenInverseTable = "oauth_tokens"
	// TokenColumn is the table column denoting the token relation/edge.
	TokenColumn = "oauth_user_authorization_token"
)

// Columns holds all SQL columns for oauthuserauthorization fields.
var Columns = []string{
	FieldID,
	FieldCreateTime,
	FieldCreateBy,
	FieldUpdateTime,
	FieldUpdateBy,
	FieldDeleteTime,
	FieldDeleteBy,
	FieldUserID,
	FieldApplicationID,
	FieldAuthorizedAt,
	FieldUsageState,
	FieldScope,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "oauth_user_authorizations"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"oauth_application_user_authorizations",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "go-backend/database/ent/runtime"
var (
	Hooks        [4]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime func() time.Time
	// DefaultUpdateTime holds the default value on creation for the "update_time" field.
	DefaultUpdateTime func() time.Time
	// UpdateDefaultUpdateTime holds the default value on update for the "update_time" field.
	UpdateDefaultUpdateTime func() time.Time
)

// UsageState defines the type for the "usage_state" enum field.
type UsageState string

// UsageStateUnused is the default value of the UsageState enum.
const DefaultUsageState = UsageStateUnused

// UsageState values.
const (
	UsageStateUnused  UsageState = "unused"
	UsageStateGranted UsageState = "granted"
	UsageStateDenied  UsageState = "denied"
	UsageStateRevoked UsageState = "revoked"
)

func (us UsageState) String() string {
	return string(us)
}

// UsageStateValidator is a validator for the "usage_state" field enum values. It is called by the builders before save.
func UsageStateValidator(us UsageState) error {
	switch us {
	case UsageStateUnused, UsageStateGranted, UsageStateDenied, UsageStateRevoked:
		return nil
	default:
		return fmt.Errorf("oauthuserauthorization: invalid enum value for usage_state field: %q", us)
	}
}

// OrderOption defines the ordering options for the OauthUserAuthorization queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByCreateBy orders the results by the create_by field.
func ByCreateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateBy, opts...).ToFunc()
}

// ByUpdateTime orders the results by the update_time field.
func ByUpdateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTime, opts...).ToFunc()
}

// ByUpdateBy orders the results by the update_by field.
func ByUpdateBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateBy, opts...).ToFunc()
}

// ByDeleteTime orders the results by the delete_time field.
func ByDeleteTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteTime, opts...).ToFunc()
}

// ByDeleteBy orders the results by the delete_by field.
func ByDeleteBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeleteBy, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByApplicationID orders the results by the application_id field.
func ByApplicationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApplicationID, opts...).ToFunc()
}

// ByAuthorizedAt orders the results by the authorized_at field.
func ByAuthorizedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorizedAt, opts...).ToFunc()
}

// ByUsageState orders the results by the usage_state field.
func ByUsageState(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsageState, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByApplicationField orders the results by application field.
func ByApplicationField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newApplicationStep(), sql.OrderByField(field, opts...))
	}
}

// ByCodeField orders the results by code field.
func ByCodeField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCodeStep(), sql.OrderByField(field, opts...))
	}
}

// ByTokenField orders the results by token field.
func ByTokenField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTokenStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
	)
}
func newApplicationStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ApplicationInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ApplicationTable, ApplicationColumn),
	)
}
func newCodeStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CodeInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, CodeTable, CodeColumn),
	)
}
func newTokenStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TokenInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, TokenTable, TokenColumn),
	)
}
