// Code generated by ent, DO NOT EDIT.

package oauthuserauthorization

import (
	"go-backend/database/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldLTE(FieldID, id))
}

// CreateTime applies equality check predicate on the "create_time" field. It's identical to CreateTimeEQ.
func CreateTime(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldCreateTime, v))
}

// CreateBy applies equality check predicate on the "create_by" field. It's identical to CreateByEQ.
func CreateBy(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldCreateBy, v))
}

// UpdateTime applies equality check predicate on the "update_time" field. It's identical to UpdateTimeEQ.
func UpdateTime(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateBy applies equality check predicate on the "update_by" field. It's identical to UpdateByEQ.
func UpdateBy(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldUpdateBy, v))
}

// DeleteTime applies equality check predicate on the "delete_time" field. It's identical to DeleteTimeEQ.
func DeleteTime(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteBy applies equality check predicate on the "delete_by" field. It's identical to DeleteByEQ.
func DeleteBy(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldDeleteBy, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldUserID, v))
}

// ApplicationID applies equality check predicate on the "application_id" field. It's identical to ApplicationIDEQ.
func ApplicationID(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldApplicationID, v))
}

// AuthorizedAt applies equality check predicate on the "authorized_at" field. It's identical to AuthorizedAtEQ.
func AuthorizedAt(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldAuthorizedAt, v))
}

// CreateTimeEQ applies the EQ predicate on the "create_time" field.
func CreateTimeEQ(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldCreateTime, v))
}

// CreateTimeNEQ applies the NEQ predicate on the "create_time" field.
func CreateTimeNEQ(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNEQ(FieldCreateTime, v))
}

// CreateTimeIn applies the In predicate on the "create_time" field.
func CreateTimeIn(vs ...time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldIn(FieldCreateTime, vs...))
}

// CreateTimeNotIn applies the NotIn predicate on the "create_time" field.
func CreateTimeNotIn(vs ...time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNotIn(FieldCreateTime, vs...))
}

// CreateTimeGT applies the GT predicate on the "create_time" field.
func CreateTimeGT(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldGT(FieldCreateTime, v))
}

// CreateTimeGTE applies the GTE predicate on the "create_time" field.
func CreateTimeGTE(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldGTE(FieldCreateTime, v))
}

// CreateTimeLT applies the LT predicate on the "create_time" field.
func CreateTimeLT(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldLT(FieldCreateTime, v))
}

// CreateTimeLTE applies the LTE predicate on the "create_time" field.
func CreateTimeLTE(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldLTE(FieldCreateTime, v))
}

// CreateByEQ applies the EQ predicate on the "create_by" field.
func CreateByEQ(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldCreateBy, v))
}

// CreateByNEQ applies the NEQ predicate on the "create_by" field.
func CreateByNEQ(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNEQ(FieldCreateBy, v))
}

// CreateByIn applies the In predicate on the "create_by" field.
func CreateByIn(vs ...uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldIn(FieldCreateBy, vs...))
}

// CreateByNotIn applies the NotIn predicate on the "create_by" field.
func CreateByNotIn(vs ...uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNotIn(FieldCreateBy, vs...))
}

// CreateByGT applies the GT predicate on the "create_by" field.
func CreateByGT(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldGT(FieldCreateBy, v))
}

// CreateByGTE applies the GTE predicate on the "create_by" field.
func CreateByGTE(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldGTE(FieldCreateBy, v))
}

// CreateByLT applies the LT predicate on the "create_by" field.
func CreateByLT(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldLT(FieldCreateBy, v))
}

// CreateByLTE applies the LTE predicate on the "create_by" field.
func CreateByLTE(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldLTE(FieldCreateBy, v))
}

// CreateByIsNil applies the IsNil predicate on the "create_by" field.
func CreateByIsNil() predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldIsNull(FieldCreateBy))
}

// CreateByNotNil applies the NotNil predicate on the "create_by" field.
func CreateByNotNil() predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNotNull(FieldCreateBy))
}

// UpdateTimeEQ applies the EQ predicate on the "update_time" field.
func UpdateTimeEQ(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldUpdateTime, v))
}

// UpdateTimeNEQ applies the NEQ predicate on the "update_time" field.
func UpdateTimeNEQ(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNEQ(FieldUpdateTime, v))
}

// UpdateTimeIn applies the In predicate on the "update_time" field.
func UpdateTimeIn(vs ...time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldIn(FieldUpdateTime, vs...))
}

// UpdateTimeNotIn applies the NotIn predicate on the "update_time" field.
func UpdateTimeNotIn(vs ...time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNotIn(FieldUpdateTime, vs...))
}

// UpdateTimeGT applies the GT predicate on the "update_time" field.
func UpdateTimeGT(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldGT(FieldUpdateTime, v))
}

// UpdateTimeGTE applies the GTE predicate on the "update_time" field.
func UpdateTimeGTE(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldGTE(FieldUpdateTime, v))
}

// UpdateTimeLT applies the LT predicate on the "update_time" field.
func UpdateTimeLT(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldLT(FieldUpdateTime, v))
}

// UpdateTimeLTE applies the LTE predicate on the "update_time" field.
func UpdateTimeLTE(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldLTE(FieldUpdateTime, v))
}

// UpdateByEQ applies the EQ predicate on the "update_by" field.
func UpdateByEQ(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldUpdateBy, v))
}

// UpdateByNEQ applies the NEQ predicate on the "update_by" field.
func UpdateByNEQ(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNEQ(FieldUpdateBy, v))
}

// UpdateByIn applies the In predicate on the "update_by" field.
func UpdateByIn(vs ...uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldIn(FieldUpdateBy, vs...))
}

// UpdateByNotIn applies the NotIn predicate on the "update_by" field.
func UpdateByNotIn(vs ...uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNotIn(FieldUpdateBy, vs...))
}

// UpdateByGT applies the GT predicate on the "update_by" field.
func UpdateByGT(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldGT(FieldUpdateBy, v))
}

// UpdateByGTE applies the GTE predicate on the "update_by" field.
func UpdateByGTE(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldGTE(FieldUpdateBy, v))
}

// UpdateByLT applies the LT predicate on the "update_by" field.
func UpdateByLT(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldLT(FieldUpdateBy, v))
}

// UpdateByLTE applies the LTE predicate on the "update_by" field.
func UpdateByLTE(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldLTE(FieldUpdateBy, v))
}

// UpdateByIsNil applies the IsNil predicate on the "update_by" field.
func UpdateByIsNil() predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldIsNull(FieldUpdateBy))
}

// UpdateByNotNil applies the NotNil predicate on the "update_by" field.
func UpdateByNotNil() predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNotNull(FieldUpdateBy))
}

// DeleteTimeEQ applies the EQ predicate on the "delete_time" field.
func DeleteTimeEQ(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldDeleteTime, v))
}

// DeleteTimeNEQ applies the NEQ predicate on the "delete_time" field.
func DeleteTimeNEQ(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNEQ(FieldDeleteTime, v))
}

// DeleteTimeIn applies the In predicate on the "delete_time" field.
func DeleteTimeIn(vs ...time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldIn(FieldDeleteTime, vs...))
}

// DeleteTimeNotIn applies the NotIn predicate on the "delete_time" field.
func DeleteTimeNotIn(vs ...time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNotIn(FieldDeleteTime, vs...))
}

// DeleteTimeGT applies the GT predicate on the "delete_time" field.
func DeleteTimeGT(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldGT(FieldDeleteTime, v))
}

// DeleteTimeGTE applies the GTE predicate on the "delete_time" field.
func DeleteTimeGTE(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldGTE(FieldDeleteTime, v))
}

// DeleteTimeLT applies the LT predicate on the "delete_time" field.
func DeleteTimeLT(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldLT(FieldDeleteTime, v))
}

// DeleteTimeLTE applies the LTE predicate on the "delete_time" field.
func DeleteTimeLTE(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldLTE(FieldDeleteTime, v))
}

// DeleteTimeIsNil applies the IsNil predicate on the "delete_time" field.
func DeleteTimeIsNil() predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldIsNull(FieldDeleteTime))
}

// DeleteTimeNotNil applies the NotNil predicate on the "delete_time" field.
func DeleteTimeNotNil() predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNotNull(FieldDeleteTime))
}

// DeleteByEQ applies the EQ predicate on the "delete_by" field.
func DeleteByEQ(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldDeleteBy, v))
}

// DeleteByNEQ applies the NEQ predicate on the "delete_by" field.
func DeleteByNEQ(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNEQ(FieldDeleteBy, v))
}

// DeleteByIn applies the In predicate on the "delete_by" field.
func DeleteByIn(vs ...uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldIn(FieldDeleteBy, vs...))
}

// DeleteByNotIn applies the NotIn predicate on the "delete_by" field.
func DeleteByNotIn(vs ...uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNotIn(FieldDeleteBy, vs...))
}

// DeleteByGT applies the GT predicate on the "delete_by" field.
func DeleteByGT(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldGT(FieldDeleteBy, v))
}

// DeleteByGTE applies the GTE predicate on the "delete_by" field.
func DeleteByGTE(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldGTE(FieldDeleteBy, v))
}

// DeleteByLT applies the LT predicate on the "delete_by" field.
func DeleteByLT(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldLT(FieldDeleteBy, v))
}

// DeleteByLTE applies the LTE predicate on the "delete_by" field.
func DeleteByLTE(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldLTE(FieldDeleteBy, v))
}

// DeleteByIsNil applies the IsNil predicate on the "delete_by" field.
func DeleteByIsNil() predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldIsNull(FieldDeleteBy))
}

// DeleteByNotNil applies the NotNil predicate on the "delete_by" field.
func DeleteByNotNil() predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNotNull(FieldDeleteBy))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNotIn(FieldUserID, vs...))
}

// ApplicationIDEQ applies the EQ predicate on the "application_id" field.
func ApplicationIDEQ(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldApplicationID, v))
}

// ApplicationIDNEQ applies the NEQ predicate on the "application_id" field.
func ApplicationIDNEQ(v uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNEQ(FieldApplicationID, v))
}

// ApplicationIDIn applies the In predicate on the "application_id" field.
func ApplicationIDIn(vs ...uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldIn(FieldApplicationID, vs...))
}

// ApplicationIDNotIn applies the NotIn predicate on the "application_id" field.
func ApplicationIDNotIn(vs ...uint64) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNotIn(FieldApplicationID, vs...))
}

// AuthorizedAtEQ applies the EQ predicate on the "authorized_at" field.
func AuthorizedAtEQ(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldAuthorizedAt, v))
}

// AuthorizedAtNEQ applies the NEQ predicate on the "authorized_at" field.
func AuthorizedAtNEQ(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNEQ(FieldAuthorizedAt, v))
}

// AuthorizedAtIn applies the In predicate on the "authorized_at" field.
func AuthorizedAtIn(vs ...time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldIn(FieldAuthorizedAt, vs...))
}

// AuthorizedAtNotIn applies the NotIn predicate on the "authorized_at" field.
func AuthorizedAtNotIn(vs ...time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNotIn(FieldAuthorizedAt, vs...))
}

// AuthorizedAtGT applies the GT predicate on the "authorized_at" field.
func AuthorizedAtGT(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldGT(FieldAuthorizedAt, v))
}

// AuthorizedAtGTE applies the GTE predicate on the "authorized_at" field.
func AuthorizedAtGTE(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldGTE(FieldAuthorizedAt, v))
}

// AuthorizedAtLT applies the LT predicate on the "authorized_at" field.
func AuthorizedAtLT(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldLT(FieldAuthorizedAt, v))
}

// AuthorizedAtLTE applies the LTE predicate on the "authorized_at" field.
func AuthorizedAtLTE(v time.Time) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldLTE(FieldAuthorizedAt, v))
}

// UsageStateEQ applies the EQ predicate on the "usage_state" field.
func UsageStateEQ(v UsageState) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldEQ(FieldUsageState, v))
}

// UsageStateNEQ applies the NEQ predicate on the "usage_state" field.
func UsageStateNEQ(v UsageState) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNEQ(FieldUsageState, v))
}

// UsageStateIn applies the In predicate on the "usage_state" field.
func UsageStateIn(vs ...UsageState) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldIn(FieldUsageState, vs...))
}

// UsageStateNotIn applies the NotIn predicate on the "usage_state" field.
func UsageStateNotIn(vs ...UsageState) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.FieldNotIn(FieldUsageState, vs...))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasApplication applies the HasEdge predicate on the "application" edge.
func HasApplication() predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, ApplicationTable, ApplicationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasApplicationWith applies the HasEdge predicate on the "application" edge with a given conditions (other predicates).
func HasApplicationWith(preds ...predicate.OauthApplication) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(func(s *sql.Selector) {
		step := newApplicationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCode applies the HasEdge predicate on the "code" edge.
func HasCode() predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, CodeTable, CodeColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCodeWith applies the HasEdge predicate on the "code" edge with a given conditions (other predicates).
func HasCodeWith(preds ...predicate.OauthAuthorizationCode) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(func(s *sql.Selector) {
		step := newCodeStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasToken applies the HasEdge predicate on the "token" edge.
func HasToken() predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, TokenTable, TokenColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTokenWith applies the HasEdge predicate on the "token" edge with a given conditions (other predicates).
func HasTokenWith(preds ...predicate.OauthToken) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(func(s *sql.Selector) {
		step := newTokenStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OauthUserAuthorization) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OauthUserAuthorization) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OauthUserAuthorization) predicate.OauthUserAuthorization {
	return predicate.OauthUserAuthorization(sql.NotPredicates(p))
}
