// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-backend/database/ent/oauthprovider"
	"go-backend/database/ent/oauthstate"
	"go-backend/database/ent/oauthuser"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OauthProviderCreate is the builder for creating a OauthProvider entity.
type OauthProviderCreate struct {
	config
	mutation *OauthProviderMutation
	hooks    []Hook
}

// SetCreateTime sets the "create_time" field.
func (_c *OauthProviderCreate) SetCreateTime(v time.Time) *OauthProviderCreate {
	_c.mutation.SetCreateTime(v)
	return _c
}

// SetNillableCreateTime sets the "create_time" field if the given value is not nil.
func (_c *OauthProviderCreate) SetNillableCreateTime(v *time.Time) *OauthProviderCreate {
	if v != nil {
		_c.SetCreateTime(*v)
	}
	return _c
}

// SetCreateBy sets the "create_by" field.
func (_c *OauthProviderCreate) SetCreateBy(v uint64) *OauthProviderCreate {
	_c.mutation.SetCreateBy(v)
	return _c
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_c *OauthProviderCreate) SetNillableCreateBy(v *uint64) *OauthProviderCreate {
	if v != nil {
		_c.SetCreateBy(*v)
	}
	return _c
}

// SetUpdateTime sets the "update_time" field.
func (_c *OauthProviderCreate) SetUpdateTime(v time.Time) *OauthProviderCreate {
	_c.mutation.SetUpdateTime(v)
	return _c
}

// SetNillableUpdateTime sets the "update_time" field if the given value is not nil.
func (_c *OauthProviderCreate) SetNillableUpdateTime(v *time.Time) *OauthProviderCreate {
	if v != nil {
		_c.SetUpdateTime(*v)
	}
	return _c
}

// SetUpdateBy sets the "update_by" field.
func (_c *OauthProviderCreate) SetUpdateBy(v uint64) *OauthProviderCreate {
	_c.mutation.SetUpdateBy(v)
	return _c
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_c *OauthProviderCreate) SetNillableUpdateBy(v *uint64) *OauthProviderCreate {
	if v != nil {
		_c.SetUpdateBy(*v)
	}
	return _c
}

// SetDeleteTime sets the "delete_time" field.
func (_c *OauthProviderCreate) SetDeleteTime(v time.Time) *OauthProviderCreate {
	_c.mutation.SetDeleteTime(v)
	return _c
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_c *OauthProviderCreate) SetNillableDeleteTime(v *time.Time) *OauthProviderCreate {
	if v != nil {
		_c.SetDeleteTime(*v)
	}
	return _c
}

// SetDeleteBy sets the "delete_by" field.
func (_c *OauthProviderCreate) SetDeleteBy(v uint64) *OauthProviderCreate {
	_c.mutation.SetDeleteBy(v)
	return _c
}

// SetNillableDeleteBy sets the "delete_by" field if the given value is not nil.
func (_c *OauthProviderCreate) SetNillableDeleteBy(v *uint64) *OauthProviderCreate {
	if v != nil {
		_c.SetDeleteBy(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *OauthProviderCreate) SetType(v oauthprovider.Type) *OauthProviderCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetName sets the "name" field.
func (_c *OauthProviderCreate) SetName(v string) *OauthProviderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetAuthorizationEndpoint sets the "authorization_endpoint" field.
func (_c *OauthProviderCreate) SetAuthorizationEndpoint(v string) *OauthProviderCreate {
	_c.mutation.SetAuthorizationEndpoint(v)
	return _c
}

// SetTokenEndpoint sets the "token_endpoint" field.
func (_c *OauthProviderCreate) SetTokenEndpoint(v string) *OauthProviderCreate {
	_c.mutation.SetTokenEndpoint(v)
	return _c
}

// SetUserInfoEndpoint sets the "user_info_endpoint" field.
func (_c *OauthProviderCreate) SetUserInfoEndpoint(v string) *OauthProviderCreate {
	_c.mutation.SetUserInfoEndpoint(v)
	return _c
}

// SetRevokeEndpoint sets the "revoke_endpoint" field.
func (_c *OauthProviderCreate) SetRevokeEndpoint(v string) *OauthProviderCreate {
	_c.mutation.SetRevokeEndpoint(v)
	return _c
}

// SetNillableRevokeEndpoint sets the "revoke_endpoint" field if the given value is not nil.
func (_c *OauthProviderCreate) SetNillableRevokeEndpoint(v *string) *OauthProviderCreate {
	if v != nil {
		_c.SetRevokeEndpoint(*v)
	}
	return _c
}

// SetRefreshEndpoint sets the "refresh_endpoint" field.
func (_c *OauthProviderCreate) SetRefreshEndpoint(v string) *OauthProviderCreate {
	_c.mutation.SetRefreshEndpoint(v)
	return _c
}

// SetNillableRefreshEndpoint sets the "refresh_endpoint" field if the given value is not nil.
func (_c *OauthProviderCreate) SetNillableRefreshEndpoint(v *string) *OauthProviderCreate {
	if v != nil {
		_c.SetRefreshEndpoint(*v)
	}
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OauthProviderCreate) SetClientID(v string) *OauthProviderCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetClientSecret sets the "client_secret" field.
func (_c *OauthProviderCreate) SetClientSecret(v string) *OauthProviderCreate {
	_c.mutation.SetClientSecret(v)
	return _c
}

// SetRedirectURI sets the "redirect_uri" field.
func (_c *OauthProviderCreate) SetRedirectURI(v string) *OauthProviderCreate {
	_c.mutation.SetRedirectURI(v)
	return _c
}

// SetScopes sets the "scopes" field.
func (_c *OauthProviderCreate) SetScopes(v []string) *OauthProviderCreate {
	_c.mutation.SetScopes(v)
	return _c
}

// SetAutoRegister sets the "auto_register" field.
func (_c *OauthProviderCreate) SetAutoRegister(v bool) *OauthProviderCreate {
	_c.mutation.SetAutoRegister(v)
	return _c
}

// SetNillableAutoRegister sets the "auto_register" field if the given value is not nil.
func (_c *OauthProviderCreate) SetNillableAutoRegister(v *bool) *OauthProviderCreate {
	if v != nil {
		_c.SetAutoRegister(*v)
	}
	return _c
}

// SetAbleState sets the "able_state" field.
func (_c *OauthProviderCreate) SetAbleState(v oauthprovider.AbleState) *OauthProviderCreate {
	_c.mutation.SetAbleState(v)
	return _c
}

// SetNillableAbleState sets the "able_state" field if the given value is not nil.
func (_c *OauthProviderCreate) SetNillableAbleState(v *oauthprovider.AbleState) *OauthProviderCreate {
	if v != nil {
		_c.SetAbleState(*v)
	}
	return _c
}

// SetMetadata sets the "metadata" field.
func (_c *OauthProviderCreate) SetMetadata(v map[string]interface{}) *OauthProviderCreate {
	_c.mutation.SetMetadata(v)
	return _c
}

// SetID sets the "id" field.
func (_c *OauthProviderCreate) SetID(v uint64) *OauthProviderCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddStateIDs adds the "states" edge to the OauthState entity by IDs.
func (_c *OauthProviderCreate) AddStateIDs(ids ...uint64) *OauthProviderCreate {
	_c.mutation.AddStateIDs(ids...)
	return _c
}

// AddStates adds the "states" edges to the OauthState entity.
func (_c *OauthProviderCreate) AddStates(v ...*OauthState) *OauthProviderCreate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddStateIDs(ids...)
}

// AddOauthUserIDs adds the "oauth_users" edge to the OauthUser entity by IDs.
func (_c *OauthProviderCreate) AddOauthUserIDs(ids ...uint64) *OauthProviderCreate {
	_c.mutation.AddOauthUserIDs(ids...)
	return _c
}

// AddOauthUsers adds the "oauth_users" edges to the OauthUser entity.
func (_c *OauthProviderCreate) AddOauthUsers(v ...*OauthUser) *OauthProviderCreate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddOauthUserIDs(ids...)
}

// Mutation returns the OauthProviderMutation object of the builder.
func (_c *OauthProviderCreate) Mutation() *OauthProviderMutation {
	return _c.mutation
}

// Save creates the OauthProvider in the database.
func (_c *OauthProviderCreate) Save(ctx context.Context) (*OauthProvider, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OauthProviderCreate) SaveX(ctx context.Context) *OauthProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OauthProviderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OauthProviderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OauthProviderCreate) defaults() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		if oauthprovider.DefaultCreateTime == nil {
			return fmt.Errorf("ent: uninitialized oauthprovider.DefaultCreateTime (forgotten import ent/runtime?)")
		}
		v := oauthprovider.DefaultCreateTime()
		_c.mutation.SetCreateTime(v)
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		if oauthprovider.DefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized oauthprovider.DefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := oauthprovider.DefaultUpdateTime()
		_c.mutation.SetUpdateTime(v)
	}
	if _, ok := _c.mutation.AutoRegister(); !ok {
		v := oauthprovider.DefaultAutoRegister
		_c.mutation.SetAutoRegister(v)
	}
	if _, ok := _c.mutation.AbleState(); !ok {
		v := oauthprovider.DefaultAbleState
		_c.mutation.SetAbleState(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *OauthProviderCreate) check() error {
	if _, ok := _c.mutation.CreateTime(); !ok {
		return &ValidationError{Name: "create_time", err: errors.New(`ent: missing required field "OauthProvider.create_time"`)}
	}
	if _, ok := _c.mutation.UpdateTime(); !ok {
		return &ValidationError{Name: "update_time", err: errors.New(`ent: missing required field "OauthProvider.update_time"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "OauthProvider.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := oauthprovider.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "OauthProvider.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OauthProvider.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := oauthprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OauthProvider.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthorizationEndpoint(); !ok {
		return &ValidationError{Name: "authorization_endpoint", err: errors.New(`ent: missing required field "OauthProvider.authorization_endpoint"`)}
	}
	if v, ok := _c.mutation.AuthorizationEndpoint(); ok {
		if err := oauthprovider.AuthorizationEndpointValidator(v); err != nil {
			return &ValidationError{Name: "authorization_endpoint", err: fmt.Errorf(`ent: validator failed for field "OauthProvider.authorization_endpoint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TokenEndpoint(); !ok {
		return &ValidationError{Name: "token_endpoint", err: errors.New(`ent: missing required field "OauthProvider.token_endpoint"`)}
	}
	if v, ok := _c.mutation.TokenEndpoint(); ok {
		if err := oauthprovider.TokenEndpointValidator(v); err != nil {
			return &ValidationError{Name: "token_endpoint", err: fmt.Errorf(`ent: validator failed for field "OauthProvider.token_endpoint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserInfoEndpoint(); !ok {
		return &ValidationError{Name: "user_info_endpoint", err: errors.New(`ent: missing required field "OauthProvider.user_info_endpoint"`)}
	}
	if v, ok := _c.mutation.UserInfoEndpoint(); ok {
		if err := oauthprovider.UserInfoEndpointValidator(v); err != nil {
			return &ValidationError{Name: "user_info_endpoint", err: fmt.Errorf(`ent: validator failed for field "OauthProvider.user_info_endpoint": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RevokeEndpoint(); ok {
		if err := oauthprovider.RevokeEndpointValidator(v); err != nil {
			return &ValidationError{Name: "revoke_endpoint", err: fmt.Errorf(`ent: validator failed for field "OauthProvider.revoke_endpoint": %w`, err)}
		}
	}
	if v, ok := _c.mutation.RefreshEndpoint(); ok {
		if err := oauthprovider.RefreshEndpointValidator(v); err != nil {
			return &ValidationError{Name: "refresh_endpoint", err: fmt.Errorf(`ent: validator failed for field "OauthProvider.refresh_endpoint": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OauthProvider.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauthprovider.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OauthProvider.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientSecret(); !ok {
		return &ValidationError{Name: "client_secret", err: errors.New(`ent: missing required field "OauthProvider.client_secret"`)}
	}
	if v, ok := _c.mutation.ClientSecret(); ok {
		if err := oauthprovider.ClientSecretValidator(v); err != nil {
			return &ValidationError{Name: "client_secret", err: fmt.Errorf(`ent: validator failed for field "OauthProvider.client_secret": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RedirectURI(); !ok {
		return &ValidationError{Name: "redirect_uri", err: errors.New(`ent: missing required field "OauthProvider.redirect_uri"`)}
	}
	if v, ok := _c.mutation.RedirectURI(); ok {
		if err := oauthprovider.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OauthProvider.redirect_uri": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AutoRegister(); !ok {
		return &ValidationError{Name: "auto_register", err: errors.New(`ent: missing required field "OauthProvider.auto_register"`)}
	}
	if _, ok := _c.mutation.AbleState(); !ok {
		return &ValidationError{Name: "able_state", err: errors.New(`ent: missing required field "OauthProvider.able_state"`)}
	}
	if v, ok := _c.mutation.AbleState(); ok {
		if err := oauthprovider.AbleStateValidator(v); err != nil {
			return &ValidationError{Name: "able_state", err: fmt.Errorf(`ent: validator failed for field "OauthProvider.able_state": %w`, err)}
		}
	}
	return nil
}

func (_c *OauthProviderCreate) sqlSave(ctx context.Context) (*OauthProvider, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OauthProviderCreate) createSpec() (*OauthProvider, *sqlgraph.CreateSpec) {
	var (
		_node = &OauthProvider{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthprovider.Table, sqlgraph.NewFieldSpec(oauthprovider.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreateTime(); ok {
		_spec.SetField(oauthprovider.FieldCreateTime, field.TypeTime, value)
		_node.CreateTime = value
	}
	if value, ok := _c.mutation.CreateBy(); ok {
		_spec.SetField(oauthprovider.FieldCreateBy, field.TypeUint64, value)
		_node.CreateBy = value
	}
	if value, ok := _c.mutation.UpdateTime(); ok {
		_spec.SetField(oauthprovider.FieldUpdateTime, field.TypeTime, value)
		_node.UpdateTime = value
	}
	if value, ok := _c.mutation.UpdateBy(); ok {
		_spec.SetField(oauthprovider.FieldUpdateBy, field.TypeUint64, value)
		_node.UpdateBy = value
	}
	if value, ok := _c.mutation.DeleteTime(); ok {
		_spec.SetField(oauthprovider.FieldDeleteTime, field.TypeTime, value)
		_node.DeleteTime = value
	}
	if value, ok := _c.mutation.DeleteBy(); ok {
		_spec.SetField(oauthprovider.FieldDeleteBy, field.TypeUint64, value)
		_node.DeleteBy = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(oauthprovider.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(oauthprovider.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.AuthorizationEndpoint(); ok {
		_spec.SetField(oauthprovider.FieldAuthorizationEndpoint, field.TypeString, value)
		_node.AuthorizationEndpoint = value
	}
	if value, ok := _c.mutation.TokenEndpoint(); ok {
		_spec.SetField(oauthprovider.FieldTokenEndpoint, field.TypeString, value)
		_node.TokenEndpoint = value
	}
	if value, ok := _c.mutation.UserInfoEndpoint(); ok {
		_spec.SetField(oauthprovider.FieldUserInfoEndpoint, field.TypeString, value)
		_node.UserInfoEndpoint = value
	}
	if value, ok := _c.mutation.RevokeEndpoint(); ok {
		_spec.SetField(oauthprovider.FieldRevokeEndpoint, field.TypeString, value)
		_node.RevokeEndpoint = value
	}
	if value, ok := _c.mutation.RefreshEndpoint(); ok {
		_spec.SetField(oauthprovider.FieldRefreshEndpoint, field.TypeString, value)
		_node.RefreshEndpoint = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthprovider.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.ClientSecret(); ok {
		_spec.SetField(oauthprovider.FieldClientSecret, field.TypeString, value)
		_node.ClientSecret = value
	}
	if value, ok := _c.mutation.RedirectURI(); ok {
		_spec.SetField(oauthprovider.FieldRedirectURI, field.TypeString, value)
		_node.RedirectURI = value
	}
	if value, ok := _c.mutation.Scopes(); ok {
		_spec.SetField(oauthprovider.FieldScopes, field.TypeJSON, value)
		_node.Scopes = value
	}
	if value, ok := _c.mutation.AutoRegister(); ok {
		_spec.SetField(oauthprovider.FieldAutoRegister, field.TypeBool, value)
		_node.AutoRegister = value
	}
	if value, ok := _c.mutation.AbleState(); ok {
		_spec.SetField(oauthprovider.FieldAbleState, field.TypeEnum, value)
		_node.AbleState = value
	}
	if value, ok := _c.mutation.Metadata(); ok {
		_spec.SetField(oauthprovider.FieldMetadata, field.TypeJSON, value)
		_node.Metadata = value
	}
	if nodes := _c.mutation.StatesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthprovider.StatesTable,
			Columns: []string{oauthprovider.StatesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthstate.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.OauthUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthprovider.OauthUsersTable,
			Columns: []string{oauthprovider.OauthUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthuser.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OauthProviderCreateBulk is the builder for creating many OauthProvider entities in bulk.
type OauthProviderCreateBulk struct {
	config
	err      error
	builders []*OauthProviderCreate
}

// Save creates the OauthProvider entities in the database.
func (_c *OauthProviderCreateBulk) Save(ctx context.Context) ([]*OauthProvider, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OauthProvider, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OauthProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OauthProviderCreateBulk) SaveX(ctx context.Context) []*OauthProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OauthProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OauthProviderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
