// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"go-backend/database/ent/area"
	"go-backend/database/ent/predicate"
	"go-backend/database/ent/subway"
	"go-backend/database/ent/subwaystation"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubwayUpdate is the builder for updating Subway entities.
type SubwayUpdate struct {
	config
	hooks    []Hook
	mutation *SubwayMutation
}

// Where appends a list predicates to the SubwayUpdate builder.
func (_u *SubwayUpdate) Where(ps ...predicate.Subway) *SubwayUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCreateBy sets the "create_by" field.
func (_u *SubwayUpdate) SetCreateBy(v uint64) *SubwayUpdate {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *SubwayUpdate) SetNillableCreateBy(v *uint64) *SubwayUpdate {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *SubwayUpdate) AddCreateBy(v int64) *SubwayUpdate {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *SubwayUpdate) ClearCreateBy() *SubwayUpdate {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SubwayUpdate) SetUpdateTime(v time.Time) *SubwayUpdate {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *SubwayUpdate) SetUpdateBy(v uint64) *SubwayUpdate {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *SubwayUpdate) SetNillableUpdateBy(v *uint64) *SubwayUpdate {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *SubwayUpdate) AddUpdateBy(v int64) *SubwayUpdate {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *SubwayUpdate) ClearUpdateBy() *SubwayUpdate {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *SubwayUpdate) SetDeleteTime(v time.Time) *SubwayUpdate {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *SubwayUpdate) SetNillableDeleteTime(v *time.Time) *SubwayUpdate {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *SubwayUpdate) ClearDeleteTime() *SubwayUpdate {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetDeleteBy sets the "delete_by" field.
func (_u *SubwayUpdate) SetDeleteBy(v uint64) *SubwayUpdate {
	_u.mutation.ResetDeleteBy()
	_u.mutation.SetDeleteBy(v)
	return _u
}

// SetNillableDeleteBy sets the "delete_by" field if the given value is not nil.
func (_u *SubwayUpdate) SetNillableDeleteBy(v *uint64) *SubwayUpdate {
	if v != nil {
		_u.SetDeleteBy(*v)
	}
	return _u
}

// AddDeleteBy adds value to the "delete_by" field.
func (_u *SubwayUpdate) AddDeleteBy(v int64) *SubwayUpdate {
	_u.mutation.AddDeleteBy(v)
	return _u
}

// ClearDeleteBy clears the value of the "delete_by" field.
func (_u *SubwayUpdate) ClearDeleteBy() *SubwayUpdate {
	_u.mutation.ClearDeleteBy()
	return _u
}

// SetName sets the "name" field.
func (_u *SubwayUpdate) SetName(v string) *SubwayUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SubwayUpdate) SetNillableName(v *string) *SubwayUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAreaID sets the "area_id" field.
func (_u *SubwayUpdate) SetAreaID(v uint64) *SubwayUpdate {
	_u.mutation.SetAreaID(v)
	return _u
}

// SetNillableAreaID sets the "area_id" field if the given value is not nil.
func (_u *SubwayUpdate) SetNillableAreaID(v *uint64) *SubwayUpdate {
	if v != nil {
		_u.SetAreaID(*v)
	}
	return _u
}

// SetColor sets the "color" field.
func (_u *SubwayUpdate) SetColor(v string) *SubwayUpdate {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *SubwayUpdate) SetNillableColor(v *string) *SubwayUpdate {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// ClearColor clears the value of the "color" field.
func (_u *SubwayUpdate) ClearColor() *SubwayUpdate {
	_u.mutation.ClearColor()
	return _u
}

// SetArea sets the "area" edge to the Area entity.
func (_u *SubwayUpdate) SetArea(v *Area) *SubwayUpdate {
	return _u.SetAreaID(v.ID)
}

// AddSubwayStationIDs adds the "subway_stations" edge to the SubwayStation entity by IDs.
func (_u *SubwayUpdate) AddSubwayStationIDs(ids ...uint64) *SubwayUpdate {
	_u.mutation.AddSubwayStationIDs(ids...)
	return _u
}

// AddSubwayStations adds the "subway_stations" edges to the SubwayStation entity.
func (_u *SubwayUpdate) AddSubwayStations(v ...*SubwayStation) *SubwayUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubwayStationIDs(ids...)
}

// Mutation returns the SubwayMutation object of the builder.
func (_u *SubwayUpdate) Mutation() *SubwayMutation {
	return _u.mutation
}

// ClearArea clears the "area" edge to the Area entity.
func (_u *SubwayUpdate) ClearArea() *SubwayUpdate {
	_u.mutation.ClearArea()
	return _u
}

// ClearSubwayStations clears all "subway_stations" edges to the SubwayStation entity.
func (_u *SubwayUpdate) ClearSubwayStations() *SubwayUpdate {
	_u.mutation.ClearSubwayStations()
	return _u
}

// RemoveSubwayStationIDs removes the "subway_stations" edge to SubwayStation entities by IDs.
func (_u *SubwayUpdate) RemoveSubwayStationIDs(ids ...uint64) *SubwayUpdate {
	_u.mutation.RemoveSubwayStationIDs(ids...)
	return _u
}

// RemoveSubwayStations removes "subway_stations" edges to SubwayStation entities.
func (_u *SubwayUpdate) RemoveSubwayStations(v ...*SubwayStation) *SubwayUpdate {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubwayStationIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubwayUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubwayUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubwayUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubwayUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubwayUpdate) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if subway.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized subway.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := subway.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubwayUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := subway.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Subway.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Color(); ok {
		if err := subway.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "Subway.color": %w`, err)}
		}
	}
	if _u.mutation.AreaCleared() && len(_u.mutation.AreaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Subway.area"`)
	}
	return nil
}

func (_u *SubwayUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subway.Table, subway.Columns, sqlgraph.NewFieldSpec(subway.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(subway.FieldCreateBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(subway.FieldCreateBy, field.TypeUint64, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(subway.FieldCreateBy, field.TypeUint64)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(subway.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(subway.FieldUpdateBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(subway.FieldUpdateBy, field.TypeUint64, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(subway.FieldUpdateBy, field.TypeUint64)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(subway.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(subway.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteBy(); ok {
		_spec.SetField(subway.FieldDeleteBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDeleteBy(); ok {
		_spec.AddField(subway.FieldDeleteBy, field.TypeUint64, value)
	}
	if _u.mutation.DeleteByCleared() {
		_spec.ClearField(subway.FieldDeleteBy, field.TypeUint64)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subway.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(subway.FieldColor, field.TypeString, value)
	}
	if _u.mutation.ColorCleared() {
		_spec.ClearField(subway.FieldColor, field.TypeString)
	}
	if _u.mutation.AreaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subway.AreaTable,
			Columns: []string{subway.AreaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(area.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AreaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subway.AreaTable,
			Columns: []string{subway.AreaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(area.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubwayStationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subway.SubwayStationsTable,
			Columns: []string{subway.SubwayStationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subwaystation.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubwayStationsIDs(); len(nodes) > 0 && !_u.mutation.SubwayStationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subway.SubwayStationsTable,
			Columns: []string{subway.SubwayStationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subwaystation.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubwayStationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subway.SubwayStationsTable,
			Columns: []string{subway.SubwayStationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subwaystation.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subway.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubwayUpdateOne is the builder for updating a single Subway entity.
type SubwayUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubwayMutation
}

// SetCreateBy sets the "create_by" field.
func (_u *SubwayUpdateOne) SetCreateBy(v uint64) *SubwayUpdateOne {
	_u.mutation.ResetCreateBy()
	_u.mutation.SetCreateBy(v)
	return _u
}

// SetNillableCreateBy sets the "create_by" field if the given value is not nil.
func (_u *SubwayUpdateOne) SetNillableCreateBy(v *uint64) *SubwayUpdateOne {
	if v != nil {
		_u.SetCreateBy(*v)
	}
	return _u
}

// AddCreateBy adds value to the "create_by" field.
func (_u *SubwayUpdateOne) AddCreateBy(v int64) *SubwayUpdateOne {
	_u.mutation.AddCreateBy(v)
	return _u
}

// ClearCreateBy clears the value of the "create_by" field.
func (_u *SubwayUpdateOne) ClearCreateBy() *SubwayUpdateOne {
	_u.mutation.ClearCreateBy()
	return _u
}

// SetUpdateTime sets the "update_time" field.
func (_u *SubwayUpdateOne) SetUpdateTime(v time.Time) *SubwayUpdateOne {
	_u.mutation.SetUpdateTime(v)
	return _u
}

// SetUpdateBy sets the "update_by" field.
func (_u *SubwayUpdateOne) SetUpdateBy(v uint64) *SubwayUpdateOne {
	_u.mutation.ResetUpdateBy()
	_u.mutation.SetUpdateBy(v)
	return _u
}

// SetNillableUpdateBy sets the "update_by" field if the given value is not nil.
func (_u *SubwayUpdateOne) SetNillableUpdateBy(v *uint64) *SubwayUpdateOne {
	if v != nil {
		_u.SetUpdateBy(*v)
	}
	return _u
}

// AddUpdateBy adds value to the "update_by" field.
func (_u *SubwayUpdateOne) AddUpdateBy(v int64) *SubwayUpdateOne {
	_u.mutation.AddUpdateBy(v)
	return _u
}

// ClearUpdateBy clears the value of the "update_by" field.
func (_u *SubwayUpdateOne) ClearUpdateBy() *SubwayUpdateOne {
	_u.mutation.ClearUpdateBy()
	return _u
}

// SetDeleteTime sets the "delete_time" field.
func (_u *SubwayUpdateOne) SetDeleteTime(v time.Time) *SubwayUpdateOne {
	_u.mutation.SetDeleteTime(v)
	return _u
}

// SetNillableDeleteTime sets the "delete_time" field if the given value is not nil.
func (_u *SubwayUpdateOne) SetNillableDeleteTime(v *time.Time) *SubwayUpdateOne {
	if v != nil {
		_u.SetDeleteTime(*v)
	}
	return _u
}

// ClearDeleteTime clears the value of the "delete_time" field.
func (_u *SubwayUpdateOne) ClearDeleteTime() *SubwayUpdateOne {
	_u.mutation.ClearDeleteTime()
	return _u
}

// SetDeleteBy sets the "delete_by" field.
func (_u *SubwayUpdateOne) SetDeleteBy(v uint64) *SubwayUpdateOne {
	_u.mutation.ResetDeleteBy()
	_u.mutation.SetDeleteBy(v)
	return _u
}

// SetNillableDeleteBy sets the "delete_by" field if the given value is not nil.
func (_u *SubwayUpdateOne) SetNillableDeleteBy(v *uint64) *SubwayUpdateOne {
	if v != nil {
		_u.SetDeleteBy(*v)
	}
	return _u
}

// AddDeleteBy adds value to the "delete_by" field.
func (_u *SubwayUpdateOne) AddDeleteBy(v int64) *SubwayUpdateOne {
	_u.mutation.AddDeleteBy(v)
	return _u
}

// ClearDeleteBy clears the value of the "delete_by" field.
func (_u *SubwayUpdateOne) ClearDeleteBy() *SubwayUpdateOne {
	_u.mutation.ClearDeleteBy()
	return _u
}

// SetName sets the "name" field.
func (_u *SubwayUpdateOne) SetName(v string) *SubwayUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SubwayUpdateOne) SetNillableName(v *string) *SubwayUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAreaID sets the "area_id" field.
func (_u *SubwayUpdateOne) SetAreaID(v uint64) *SubwayUpdateOne {
	_u.mutation.SetAreaID(v)
	return _u
}

// SetNillableAreaID sets the "area_id" field if the given value is not nil.
func (_u *SubwayUpdateOne) SetNillableAreaID(v *uint64) *SubwayUpdateOne {
	if v != nil {
		_u.SetAreaID(*v)
	}
	return _u
}

// SetColor sets the "color" field.
func (_u *SubwayUpdateOne) SetColor(v string) *SubwayUpdateOne {
	_u.mutation.SetColor(v)
	return _u
}

// SetNillableColor sets the "color" field if the given value is not nil.
func (_u *SubwayUpdateOne) SetNillableColor(v *string) *SubwayUpdateOne {
	if v != nil {
		_u.SetColor(*v)
	}
	return _u
}

// ClearColor clears the value of the "color" field.
func (_u *SubwayUpdateOne) ClearColor() *SubwayUpdateOne {
	_u.mutation.ClearColor()
	return _u
}

// SetArea sets the "area" edge to the Area entity.
func (_u *SubwayUpdateOne) SetArea(v *Area) *SubwayUpdateOne {
	return _u.SetAreaID(v.ID)
}

// AddSubwayStationIDs adds the "subway_stations" edge to the SubwayStation entity by IDs.
func (_u *SubwayUpdateOne) AddSubwayStationIDs(ids ...uint64) *SubwayUpdateOne {
	_u.mutation.AddSubwayStationIDs(ids...)
	return _u
}

// AddSubwayStations adds the "subway_stations" edges to the SubwayStation entity.
func (_u *SubwayUpdateOne) AddSubwayStations(v ...*SubwayStation) *SubwayUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubwayStationIDs(ids...)
}

// Mutation returns the SubwayMutation object of the builder.
func (_u *SubwayUpdateOne) Mutation() *SubwayMutation {
	return _u.mutation
}

// ClearArea clears the "area" edge to the Area entity.
func (_u *SubwayUpdateOne) ClearArea() *SubwayUpdateOne {
	_u.mutation.ClearArea()
	return _u
}

// ClearSubwayStations clears all "subway_stations" edges to the SubwayStation entity.
func (_u *SubwayUpdateOne) ClearSubwayStations() *SubwayUpdateOne {
	_u.mutation.ClearSubwayStations()
	return _u
}

// RemoveSubwayStationIDs removes the "subway_stations" edge to SubwayStation entities by IDs.
func (_u *SubwayUpdateOne) RemoveSubwayStationIDs(ids ...uint64) *SubwayUpdateOne {
	_u.mutation.RemoveSubwayStationIDs(ids...)
	return _u
}

// RemoveSubwayStations removes "subway_stations" edges to SubwayStation entities.
func (_u *SubwayUpdateOne) RemoveSubwayStations(v ...*SubwayStation) *SubwayUpdateOne {
	ids := make([]uint64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubwayStationIDs(ids...)
}

// Where appends a list predicates to the SubwayUpdate builder.
func (_u *SubwayUpdateOne) Where(ps ...predicate.Subway) *SubwayUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubwayUpdateOne) Select(field string, fields ...string) *SubwayUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Subway entity.
func (_u *SubwayUpdateOne) Save(ctx context.Context) (*Subway, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubwayUpdateOne) SaveX(ctx context.Context) *Subway {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubwayUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubwayUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SubwayUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdateTime(); !ok {
		if subway.UpdateDefaultUpdateTime == nil {
			return fmt.Errorf("ent: uninitialized subway.UpdateDefaultUpdateTime (forgotten import ent/runtime?)")
		}
		v := subway.UpdateDefaultUpdateTime()
		_u.mutation.SetUpdateTime(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *SubwayUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := subway.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Subway.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Color(); ok {
		if err := subway.ColorValidator(v); err != nil {
			return &ValidationError{Name: "color", err: fmt.Errorf(`ent: validator failed for field "Subway.color": %w`, err)}
		}
	}
	if _u.mutation.AreaCleared() && len(_u.mutation.AreaIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Subway.area"`)
	}
	return nil
}

func (_u *SubwayUpdateOne) sqlSave(ctx context.Context) (_node *Subway, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subway.Table, subway.Columns, sqlgraph.NewFieldSpec(subway.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Subway.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subway.FieldID)
		for _, f := range fields {
			if !subway.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subway.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CreateBy(); ok {
		_spec.SetField(subway.FieldCreateBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedCreateBy(); ok {
		_spec.AddField(subway.FieldCreateBy, field.TypeUint64, value)
	}
	if _u.mutation.CreateByCleared() {
		_spec.ClearField(subway.FieldCreateBy, field.TypeUint64)
	}
	if value, ok := _u.mutation.UpdateTime(); ok {
		_spec.SetField(subway.FieldUpdateTime, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdateBy(); ok {
		_spec.SetField(subway.FieldUpdateBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUpdateBy(); ok {
		_spec.AddField(subway.FieldUpdateBy, field.TypeUint64, value)
	}
	if _u.mutation.UpdateByCleared() {
		_spec.ClearField(subway.FieldUpdateBy, field.TypeUint64)
	}
	if value, ok := _u.mutation.DeleteTime(); ok {
		_spec.SetField(subway.FieldDeleteTime, field.TypeTime, value)
	}
	if _u.mutation.DeleteTimeCleared() {
		_spec.ClearField(subway.FieldDeleteTime, field.TypeTime)
	}
	if value, ok := _u.mutation.DeleteBy(); ok {
		_spec.SetField(subway.FieldDeleteBy, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedDeleteBy(); ok {
		_spec.AddField(subway.FieldDeleteBy, field.TypeUint64, value)
	}
	if _u.mutation.DeleteByCleared() {
		_spec.ClearField(subway.FieldDeleteBy, field.TypeUint64)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(subway.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Color(); ok {
		_spec.SetField(subway.FieldColor, field.TypeString, value)
	}
	if _u.mutation.ColorCleared() {
		_spec.ClearField(subway.FieldColor, field.TypeString)
	}
	if _u.mutation.AreaCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subway.AreaTable,
			Columns: []string{subway.AreaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(area.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AreaIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   subway.AreaTable,
			Columns: []string{subway.AreaColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(area.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SubwayStationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subway.SubwayStationsTable,
			Columns: []string{subway.SubwayStationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subwaystation.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubwayStationsIDs(); len(nodes) > 0 && !_u.mutation.SubwayStationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subway.SubwayStationsTable,
			Columns: []string{subway.SubwayStationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subwaystation.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubwayStationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   subway.SubwayStationsTable,
			Columns: []string{subway.SubwayStationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subwaystation.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Subway{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subway.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
